services:
  - type: web
    name: hefestos
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
